# Generated by Django 3.2.13 on 2022-11-15 00:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images/articles/'),
        ),
        migrations.AlterField(
            model_name='region',
            name='detail_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/region/'),
        ),
        migrations.AlterField(
            model_name='region',
            name='index_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/region/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images/reviews/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/theme/'),
        ),
    ]
