# Generated by Django 3.2.13 on 2022-11-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_review_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like_user',
            new_name='like_users',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='articles',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
