# Generated by Django 3.2.13 on 2022-11-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20221114_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='location',
        ),
        migrations.RemoveField(
            model_name='article',
            name='x',
        ),
        migrations.RemoveField(
            model_name='article',
            name='y',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=300)),
                ('x', models.CharField(blank=True, max_length=100, null=True)),
                ('y', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
