# Generated by Django 3.2.13 on 2022-11-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='article',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/reviews'),
        ),
    ]
