# Generated by Django 3.2.13 on 2022-11-11 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_service', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicecomment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center', to='service_center.servicecenter'),
        ),
    ]
